version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: gantt-postgres-dev
    environment:
      POSTGRES_DB: gantt_chart_dev
      POSTGRES_USER: gantt_user
      POSTGRES_PASSWORD: gantt_password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - gantt-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gantt_user -d gantt_chart_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API Service (NestJS) - Development
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: development
    container_name: gantt-api-dev
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://gantt_user:gantt_password@postgres:5432/gantt_chart_dev
      JWT_SECRET: dev-jwt-secret-key
      PORT: 3001
    ports:
      - "3001:3001"
    volumes:
      - ./apps/api:/usr/src/app
      - ./prisma:/usr/src/app/prisma
      - /usr/src/app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - gantt-network
    restart: unless-stopped

  # Web Service (Next.js) - Development
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      target: development
    container_name: gantt-web-dev
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    depends_on:
      - api
    networks:
      - gantt-network
    restart: unless-stopped

networks:
  gantt-network:
    driver: bridge

volumes:
  postgres_dev_data:
    driver: local