services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: gantt-postgres-dev
    environment:
      POSTGRES_DB: gantt_chart_dev
      POSTGRES_USER: gantt_user
      POSTGRES_PASSWORD: gantt_password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - "5432:5432"
    networks:
      - gantt-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gantt_user -d gantt_chart_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API Service (NestJS) - Development
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: development
    container_name: gantt-api-dev
    env_file:
      - ./apps/api/.env
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://gantt_user:gantt_password@postgres:5432/gantt_chart_dev
      JWT_SECRET: dev-jwt-secret-key
      JWT_AUDIENCE: gantt-chart-web-ui
      JWT_ISSUER: gantt-chart-api
      PORT: 3001
      LOG_LEVEL: debug
      CORS_ORIGIN: http://localhost:3000
    ports:
      - "3001:3001"
    volumes:
      - ./apps/api:/usr/src/app
      - ./apps/api/prisma:/usr/src/app/prisma
      - ./packages:/usr/src/packages
      - /usr/src/app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - gantt-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Web Service (Next.js) - Development
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      target: development
    container_name: gantt-web-dev
    env_file:
      - ./apps/web/.env.local
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3001
      NEXT_PUBLIC_API_BASE: http://localhost:3001/api/v1
      # Internal API URL for server-side calls
      API_URL: http://api:3001
      API_BASE: http://api:3001/api/v1
      NEXT_TELEMETRY_DISABLED: 1
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web:/usr/src/app
      - ./packages:/usr/src/packages
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    depends_on:
      api:
        condition: service_healthy
    networks:
      - gantt-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  gantt-network:
    driver: bridge

volumes:
  postgres_dev_data:
    driver: local