version: "3.9"

services:
  db:
    image: postgres:15
    container_name: poc-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: poc
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20

  api:
    build:
      context: ../../apps/api
      dockerfile: Dockerfile
    container_name: poc-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@db:5432/poc?schema=public
      JWT_AUDIENCE: poc
      JWT_ISSUER: poc
      JWT_SECRET: dev-secret-key
      PORT: 3001
    ports:
      - "3001:3001"
    command: ["npm", "run", "start:dev"]
    volumes:
      - ../../apps/api:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  web:
    build:
      context: ../../apps/web
      dockerfile: Dockerfile
    container_name: poc-web
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_BASE: http://localhost:3001/api/v1
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]
    volumes:
      - ../../apps/web:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    restart: unless-stopped

volumes:
  pgdata: